### ISSUE TITLE
Error when render a video

### ISSUE THREAD

**Issue by aditiapratama** [EternalTrail/eeVR#1]
**Describe the bug**
Somehow rendering an animation is not working

**Console log (if an error message is produced)**
```RuntimeError: Error: Image 'Render Result' does not have any image data```

**Comment by aditiapratama** [comment]
Somehow I fix the error and it renders correctly now, I plan to contribute this project to make it proper add-ons.

**Comment by EternalTrail** [comment]
Since you seem to have fixed the problem, this issue is now closed. For future reference, if you get any errors you could include the .blend file of the project, if possible give as much information as possible such as version of blender. Thanks.
