### ISSUE TITLE
Fisheye render

### ISSUE THREAD

**Issue by ntqr** [EternalTrail/eeVR#11]
Are there any possibility of adding a feature to render out Fisheye Equidistant and Fisheye Equisolid too?

**Comment by EternalTrail** [comment]
Hi, I could have a go at creating shaders for that, just don't know when I'll have the time to do that.

**Comment by genericfit** [comment]
Hey @EternalTrail!

When I hit render image only one image is produced. Do you know why this might be?

**Comment by EternalTrail** [comment]
> Hey @EternalTrail!
> 
> When I hit render image only one image is produced. Do you know why this might be?

The rendered image will not be displayed in blender, instead it will be saved in the folder where your blend file is.

**Comment by EternalTrail** [comment]
As of the latest merge #18, the new render modes have been added. My thanks goes to @phaseIV for implementing these changes.
