### ISSUE TITLE
Recommendation settings to render 4K VR180/360

### ISSUE THREAD

**Issue by vaimd** [EternalTrail/eeVR#14]
Definitely, This script is helpful.

I'm new at VR and blender rendering.
Is there any recommendation setting for rendering to make 4K VR180/360 for Youtube, and recommendation ffmpeg command?
Please let me know..

There is sample of ffmpeg commands on Oculus blog, and it worked. But I'm not sure that it is good for eeVR(and eevee) and PNG files.
https://creator.oculus.com/blog/encoding-high-resolution-360-and-180-video-for-oculus-go/

Any suggestions would be help. Thanks!

**Comment by EternalTrail** [comment]
Encoding is separate from the rendering engine so using the same commands as shown in the link would be OK. Unfortunately eeVR doesn't support rendering straight to video yet, although that is a feature that is to be added in the future.
