### ISSUE TITLE
Super visible seams 

### ISSUE THREAD

**Issue by polidox2** [EternalTrail/eeVR#16]
Hi!
thank you very much for this awesome plugin, however there this huge issue that i experience..

https://imgur.com/a/Qe1DtlD
please look at the picture i tried to remove the Screen space reflection, i also did the overscan.. but nothing change i still experience this boring thing .

any help please its really frustrating

thank you :)

**Comment by EternalTrail** [comment]
Hello, would you be able to provide a .blend file for testing purposes? Could you also list what plugins you were using?

**Comment by burnheads** [comment]
Hello, very awesome plugin, but I can confirm that there is very visible seams.
I can reduce the effect using 10% overscan but can't eliminate it.

tank you

**Comment by polidox2** [comment]
thank you i've moved to cycle rendering, but i can also confirm that seams are there.

**Comment by EternalTrail** [comment]
Hi,

When you move to cycles this addon becomes redundant. You can render 180
and 360 degree imagery natively in cycles.

Kind regards,
Andrius Vaicaitis

**Comment by SAM-tak** [comment]
Already supported
