### ISSUE TITLE
Enabling motion blur makes blender stop responing when you render

### ISSUE THREAD

**Issue by coobenguy** [EternalTrail/eeVR#19]
After enabling motion blur and going to render, blender will stop responding indefinitely. It doent even load anything into ram.

OS: win 10
CPU: ryzen 5 2600
Graphics card: 1080 TI
Graphics driver: 27.21.14.5206
Blender version: 2.90.1 (aslo doesnt work in 2.9 or 2.8 from what I can tell)

**Comment by SAM-tak** [comment]
Unable to reproduce.
