### ISSUE TITLE
Error while selecting options

### ISSUE THREAD

**Issue by kinectsources** [EternalTrail/eeVR#2]
![Screenshot (123)](https://user-images.githubusercontent.com/48123837/67637532-7bdee700-f901-11e9-8ea1-d4da15dcb637.png)
getting error while selecting oprtions....and I am using stable 2.80

**Comment by EternalTrail** [comment]
Have you saved the .blend file? The error seems to be that the permission is denied, which can happen if the blend file is not saved, or if your blend file is stored in a directory which is write protected. You can try saving the project in a separate directory (like your documents) or running blender with admin rights.

**Comment by kinectsources** [comment]
Yes it's working
