### ISSUE TITLE
does not render alpha as transparency

### ISSUE THREAD

**Issue by mikemeyers1** [EternalTrail/eeVR#20]
When rendering animation with film set to transparent, background is rendered as black rather than transparent.

**Comment by EternalTrail** [comment]
I think this might be due to the way the pixel info is copied during the projection. I will try figuring this out at some point.

**Comment by garyritchie** [comment]
@SAM-tak I was wondering if this was on your radar or to-do list.

**Comment by SAM-tak** [comment]
@garyritchie 
I find it curious that there is a demand for this, as I've never personally felt the need for results with an alpha channel. When would it be useful? If it's something easily achievable, I might consider giving it a try.

**Comment by garyritchie** [comment]
@SAM-tak 
It can be useful for rendering elements/layers to mix with in the compositing stage -- foreground elements over background. The ideal output would be layered EXR. A composite can mix renders from Unreal or Cycles or even the compositor. This is for planetarium projection.

Also watching this with great interest: https://projects.blender.org/blender/blender/issues/93220#user-content-extended-target (panoramic camera)

**Comment by SAM-tak** [comment]
Done #57
