### ISSUE TITLE
Can't making the character suite my size

### ISSUE THREAD

**Issue by qsqsaaw** [EternalTrail/eeVR#21]
My render result is giant when i watching it in skybox player on quest2.
I render it with 180degree.
I tried scaling model, putting camera closer to model, but no helps.

**Comment by nagadomi** [comment]
The size of model in VR depends on  `Camera >  Stereoscope > Interocular distance`.
The default `0.065 m` is the distance between the eyes of an average person.
If the model is huge on the blender scale, setting `interocular_distance = (model_height_in_blender_scale / model_ideal_height) * 0.065` should fix it.

**Comment by qsqsaaw** [comment]
> The size of model in VR depends on `Camera > Stereoscope > Interocular distance`.
> The default `0.065 m` is the distance between the eyes of an average person.
> If the model is huge on the blender scale, setting `interocular_distance = (model_height_in_blender_scale / model_ideal_height) * 0.065` should fix it.

Model is big like before when changing the value to 0.0065

**Comment by jehuty1980** [comment]
> > The size of model in VR depends on `Camera > Stereoscope > Interocular distance`.
> > The default `0.065 m` is the distance between the eyes of an average person.
> > If the model is huge on the blender scale, setting `interocular_distance = (model_height_in_blender_scale / model_ideal_height) * 0.065` should fix it.
> 
> Model is big like before when changing the value to 0.0065
Not 0.0065, nagadomi has given a formula.
Calculate it or just seting that value to 1m to see whether is works.

**Comment by nagadomi** [comment]
Yes. If the model height is 20m on the blender scale and you want it to be 158cm in VR.
`interocular_distance = (20 / 1.58) * 0.065 = 0.8228` (rounded)
The model height can be measured `3D View > Item Tab > Transform > Dimensions > Z` or using the Measure tool.

 (The model height loaded with the default settings of [mmd_tools](https://github.com/powroupi/blender_mmd_tools) is about 20m. I had assumed that qsqsaaw is a user of mmd_tools.)

**Comment by qsqsaaw** [comment]
> Yes. If the model height is 20m on the blender scale and you want it to be 158cm in VR.
> `interocular_distance = (20 / 1.58) * 0.065 = 0.8228` (rounded)
> The model height can be measured `3D View > Item Tab > Transform > Dimensions > Z` or using the Measure tool.
> 
> (The model height loaded with the default settings of [mmd_tools](https://github.com/powroupi/blender_mmd_tools) is about 20m. I had assumed that qsqsaaw is a user of mmd_tools.)

You are right. This value is good.Thanks for your help.

**Comment by EternalTrail** [comment]
This seems to have been resolved, so I'm closing the issue for now.
