### ISSUE TITLE
AA not effective?

### ISSUE THREAD

**Issue by PaulNLNL** [EternalTrail/eeVR#26]
![image](https://user-images.githubusercontent.com/84221938/118397429-29d0f400-b654-11eb-9bbe-473461285ccb.png)
Samples are set at 64 samples but output is the same as when it is set to 1 sample.  If I use the Blender render image for the same situation it works as expected:
![image](https://user-images.githubusercontent.com/84221938/118397529-b7144880-b654-11eb-9a52-42058f0595c2.png)

**Comment by nagadomi** [comment]
It is probably a problem with the interpolation mode of the image remapping process(cubemap_to_equirectangular).
If you increase `Render properties Tab > film > Filter size`(e.g. 4), anti-aliasing will be applied more strongly, but the stretched region will be blurred.
My current workaround is to render the image at 150% size and then downscale it.
