### ISSUE TITLE
Soft shadows in the right stereoscopic camera are not rendering correctly

### ISSUE THREAD

**Issue by Da-Nuker** [EternalTrail/eeVR#28]
This is an FYI post as it is not a bug in this addon but in Blender.

If you are rendering in stereoscopic view with soft shadows activated in the scene, you will notice that in some cases the soft shadows are applied correctly in the left camera but not on the right. This will cause visual corruption issues when viewing in VR.

As a workaround, disable stereoscopy in the scene and create two separate left/right cameras separated by the local X distance of the desired IPD and render each camera view separately using eeVR. You can use another software to merge the left and right camera renders together, I used ImagicMagik as it is easy to script.

Someone else has reported this issue in Blender bug report and I verified that it still exists in 2.93: https://developer.blender.org/T84009

**Comment by EternalTrail** [comment]
Thanks for providing a workaround. I putting the "won't fix" label on this as it isn't a bug with my program, but I'll leave the issue open for people to have easier access to it.

**Comment by Da-Nuker** [comment]
Update on this issue: it should have been resolved as of Blender 2.93.6 from this fix:

https://developer.blender.org/rB22892955553e86b393dd6e6d74b2b13690c1d36b
