### ISSUE TITLE
Error Message when clicking "Render Animation"

### ISSUE THREAD

**Issue by Oxy97** [EternalTrail/eeVR#29]
Hello,

Whenever I click "Render Animation", this error box pops-up and doesn't allow me to render the animation. What am I doing wrong? 

![hh2](https://user-images.githubusercontent.com/89025354/129574732-9c88c158-c6b4-451a-b07f-184464c10191.png)

EDIT: I've fixed it by using the correct FOV. However, now it just crashes during the first frame.

**Comment by EternalTrail** [comment]
Not sure why exactly it crashes, as I don't have enough information. You can try it out on a new scene, since it's possible that it's clashing with some plugin you're using in your scene.

**Comment by jentron** [comment]
"Incorrect Context" is the bane of Blender Python programming. The context in bpy.context has to do with the state of the GUI, if your mouse is over the wrong panel or you're on the wrong tab or you're in the wrong mode, it throws context errors...

**Comment by SAM-tak** [comment]
Unable to reproduce.
