### ISSUE TITLE
360 equirectangular 

### ISSUE THREAD

**Issue by kinectsources** [EternalTrail/eeVR#3]
when I render 360 image it is rendering 360 equirectangular format probably most web viewers are panoromic support only. Can you give any suggestions for 360 image viewers?
![Render Result 2019-10-30-19-22-03](https://user-images.githubusercontent.com/48123837/68086998-9b34c180-fe77-11e9-919c-2bcc0583a081.png)

**Comment by EternalTrail** [comment]
I generally test out my renders using an app on my android device, just look up VR player on the app store and you should find one suitable. For future reference, if there's nothing wrong with the code side of this project please don't open a new issue, instead just email me at andriux19960823@gmail.com and I will try and reply asap! :)
