### ISSUE TITLE
Does EEvr support ACES shader？

### ISSUE THREAD

**Issue by bbcca9** [EternalTrail/eeVR#31]
![Cache_453e9399e1032e7a](https://user-images.githubusercontent.com/90976704/133894235-cdb16238-52b1-4c46-9b5e-ad3160dfeebc.jpg)

when choosing aces shader, eevr seems to collapse

**Comment by EternalTrail** [comment]
Support for it might be added in the future, but for now I'm not working on this project since I'm still in college.

**Comment by bbcca9** [comment]
> Support for it might be added in the future, but for now I'm not working on this project since I'm still in college.

Do you think there exist a certain amount of patronage would change your priority a little in your spare time

**Comment by EternalTrail** [comment]
> > Support for it might be added in the future, but for now I'm not working on this project since I'm still in college.
> 
> Do you think there exist a certain amount of patronage would change your priority a little in your spare time

It's possible, yes, however it probably would have to be more than most people would be willing to invest, since I value my mental health above all else.

**Comment by bbcca9** [comment]
allege it please,

**Comment by EternalTrail** [comment]
I'm not sure I understand your statement, could you elaborate, please?

**Comment by bbcca9** [comment]
> I'm not sure I understand your statement, could you elaborate, please?

just how much money do you want me to invest

**Comment by EternalTrail** [comment]
I would probably ask for hourly pay, at say €20 per hour, which is on the lower end of hourly wages that software engineers get in my country. As I said, my free time is important to me, and I'm not sure it's exactly a worthwhile. You could invest this kind of sum of into a render farm and have your projects rendered via cycles, since it support this type of rendering out of the box.

**Comment by bbcca9** [comment]
alright, if you are not sure, maybe you should prioritize on the college, i wish to see the total amount of money so as to decide.

**Comment by EternalTrail** [comment]
I'm glad to know there are people willing to invest. I will be coming back to active development of this project in about a year or two, after I finish my degree. I still might do some updates on this occasionally before I finish my degree but that's not exactly a certainty.

**Comment by SAM-tak** [comment]
Probably, it has been resolved by now.
