### ISSUE TITLE
Transparent object with alpha blend settings not visible in some part of the image

### ISSUE THREAD

**Issue by elpathooo** [EternalTrail/eeVR#34]
I have several semi-transparent objects set on the alpha blend. And there are parts of the image (middle left and right seams) where the render just clips out part of the object. When I switch to "alpha hashed" everything is normal. It started to happen recently, before it was fine. When I import models to a new file the problem stays.

![image](https://user-images.githubusercontent.com/95707695/145074348-242702e1-a3d7-4ff3-92c5-0f2019962b5f.png)

The shape is always the same as if there is some object masking it. I tried like every combination of settings I could think of and nothing changes. Besides the alpha hashed, which unfortunately adds a massive amount of time in rendering.

Thank you for your help.

**Comment by EternalTrail** [comment]
Currently eeVR ignores the alpha channel in the stitching process, which could be the issue. This is something that I will look into solving.

**Comment by SAM-tak** [comment]
Fixed in #57
