### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by NTX9** [EternalTrail/eeVR#36]
I triggered an error message by typing a bogus location into the save folder location.  I have since corrected the save location but the error message keeps coming up each time I try to render an animation and even with a single frame, the rendered output does save to the corrected location.  Is there a way to clear the error warning?

I should add that I am running Blender 3.0 on W10.

**Comment by NTX9** [comment]
![EEVR-Error](https://user-images.githubusercontent.com/31090202/148304899-e1d63926-5b4f-4c2c-8491-addfc722e4b3.png)

Here is the error message.  This appears even when I point EEVR to a directory on the C: drive.  I get the error when I try to run an animation.  If I run a single image, blender cranks up and appears to work on a rendering but no final output file gets saved to any location.

**Comment by NTX9** [comment]
I realized that this error could be related to running the script on Blender 3.0.  Tried installing 2.90 and ran a totally different scene but still get the same error.

**Comment by nagadomi** [comment]
The folder option in VRRender_ALT.py seems to expect only a subfolder name. It is not allowed to specify a folder location other than where the .blend file is located.
If you want to output the rendered image to another folder, you have to move the .blend file to the folder you want to output to.

**Comment by NTX9** [comment]
> The folder option in VRRender_ALT.py seems to expect only a subfolder name. It is not allowed to specify a folder location other than where the .blend file is located. If you want to output the rendered image to another folder, you have to move the .blend file to the folder you want to output to. To restore the default, set the folder option to empty.

Thanks!  I just set up blender on a new machine and accidentally discovered this to be the case.  It was kind of cool to watch the scrip generate multiple images and then combine them. BTW this worked in blender 3.0.

**Comment by NTX9** [comment]
This script is so freaking cool!

**Comment by SAM-tak** [comment]
Nolonger reproduce
