### ISSUE TITLE
Top-Bottom mode is upsided down

### ISSUE THREAD

**Issue by gg4869** [EternalTrail/eeVR#39]
Blender version 2.93.1 LTS.

SBS mode works perfect. 

But in top-bottom mode, top image and bottom image location is upside down. 

Other people have experiencing same issue. You can find a commend saying that he used GIMP to fix upside down image. 
: [(https://www.youtube.com/watch?v=ND8T5_VCcN0)]

**Comment by EternalTrail** [comment]
I created this program while testing with a VR player on my phone, which lead to this. It should be trivial enough to fix this.

**Comment by poufeiococ** [comment]
What does SBS mode mean? How to set it? I can't find it.

**Comment by nagadomi** [comment]
SBS means Side-by-Side. The left and right images are placed horizontally.
It is the default value. However, it can also be made explicit at `Output Properties > Output > Views`, `Views Format = Stereo 3D`, `Stereo Mode > Side-by-Side/Top-Bottom`. This property is only visible when `Output Properties > Stereoscopy` is enabled.
