### ISSUE TITLE
full dome

### ISSUE THREAD

**Issue by phaseIV** [EternalTrail/eeVR#4]
To make it work on my comp I had to rename gl_FragColor to fragColor and now it runs great!
Thank you for this code! 

Btw, i have added dome support in my fork.

**Comment by EternalTrail** [comment]
I tested out your fork and all I can say is _**very cool!**_ You can create a pull request *(if you would like)* and I will happily continue working on this code going forward! Drop me an email at [andriux19960823@gmail.com](mailto:andriux19960823@gmail.com) if you have any suggestions for future updates on this project!
