### ISSUE TITLE
wont render anything

### ISSUE THREAD

**Issue by deathedell** [EternalTrail/eeVR#50]
it just doesn't render anything, the format is set to png and it doesnt give me any errors, there is just no output. I set the file location to a folder and it doesn't go there. My blender is 3.4.1.

**Comment by Sasatari** [comment]
By default, the result is saved in the same folder where your *.blend-file lives.
Did you check there?
What´s your operating system?

**Comment by SAM-tak** [comment]
Duplicate issue
Already fixed in #51
