### ISSUE TITLE
EEVR Plugin disappeared in version 3.6 - HOW TO FIX

### ISSUE THREAD

**Issue by RenCeifer** [EternalTrail/eeVR#53]
Plugin disappeared in version 3.6

How to solve:
1-Open the plugin file "__init__.py";
2- On line 31, delete the text "support": "TESTING";
3- Save the file, and look again in the plugins list, it will be in the community tab!

**Comment by S00pergang** [comment]
This isn't working for Blender 4.0

**Comment by SAM-tak** [comment]
Already fixed in #49

**Comment by RenCeifer** [comment]
> This isn't working for Blender 4.0

Sorry but it works for me, same in 4.0:
![image](https://github.com/EternalTrail/eeVR/assets/141743561/c248f25f-c22c-48e6-b642-5aba75d231a0)

**Comment by SAM-tak** [comment]
@RenCeifer UI was moved to Properties's Render tab

**Comment by SAM-tak** [comment]
I’m sorry, I didn’t realize I hadn’t changed that part when merging. It should be fixed now.
