### ISSUE TITLE
eeVR Master is not displayed

### ISSUE THREAD

**Issue by ryottyan** [EternalTrail/eeVR#6]
Nice to meet you! I was looking forward to this wonderful script. I downloaded it immediately and installed it in the Blender 2.8 preferences add-on, but eeVR Master is not displayed. I have been worried about it for a while, so I would like to know the specific method.

**Comment by EternalTrail** [comment]
Hello! To make this work please follow the instructions on the readme page of this project. Currently, this project is just a script to adding it as an addon will not work! You need to open the script in the text editor and run it manually in your project. Hopefully, in the near future I will update this script to work as an addon!

**Comment by ryottyan** [comment]
Thank you for your quick reply. Does it mean that the script can be executed but the function is not available at this stage?

**Comment by EternalTrail** [comment]
The function works, please read the getting started guide on the main page of this project.
