### ISSUE TITLE
Rendered images being blurry compare to Cycle at same resolution 

### ISSUE THREAD

**Issue by HiandMK198** [EternalTrail/eeVR#62]
Describe the bug:
For the image rendered using eeVR, I noticed it is a bit blurry or out of focus. I have no idea why the image quality has been decreased. All the view resolution in the eeVR setting has been set to 100%. Without using the eeVR addon, the image rendered using EEVEE will not be blurry.

The way I found to neglect the effect is to scale up the image resolution. From 4k to 12k, but this also increases render time. Which defeats the purpose of using EEVEE to render an animation.

I have included a Google Drive for the Blender files for you to see which settings should and shouldn't turn on; one is using the eeVR addon, and the other is using Cycle. 
https://drive.google.com/drive/folders/1PpHxftQ1eO7Ql9sUyBaNmlJQmUDjKfuu?usp=sharing

To Reproduce:
1. Set EEVEE as the default engine
2. Set render image resolution to 4096 x 2048
3. Set Output as PNG with RGBA, Color Depth 8, Compression 0%
4. Set eeVR all view resolution to 100%
5. Hit the render images in eeVR.

Expected behavior:
It will produce a blurry image compared to the cycle.

**Screenshots**
![Screenshot 2024-04-25 150422](https://github.com/EternalTrail/eeVR/assets/167860180/06e59dae-d6e4-4d2e-ae7d-30a759a7a35e)
The right one uses Cycle, and the render is much clearer than the left one, which uses the EEVEE with eeVR.

System information:
 - Windows 10
 - Processor: i7 12700F
 - Graphics card: AMD Radeon 6800xt
 - Graphics driver: 31.0.24002.92
 - Blender version: 4.0.2

**Comment by SAM-tak** [comment]
I apologize, the part related to calculating the maximum resolution was reversed between the dome and equirectangular formats. It should be fixed now.
