### ISSUE TITLE
Side by side

### ISSUE THREAD

**Issue by yes2077** [EternalTrail/eeVR#7]
Hi! Your script is absolutely amazing and it is exactly what I searched for a long time. I know it may be difficult, but side-by-side format is more popular than top-bottom in 180° videos. I'm zero at scripts and can't rewrite it myself, can you please add this feature?

Also, I may be wrong but image renders with wrong eyes position (bottom should be for right eye and top for left eye)

And you posted a link to "VR Media Player - 360° Viewer" app on blenderartists, I used a lot of vr players including this one, and I do reccomend to try out "VRTV VR". It's fully customizable and gives best perfomance in both 180° and 360° videos

**Comment by EternalTrail** [comment]
Hello!
I have been planning on adding side-by-side but didn't since the Blender API doesn't (maybe does now) have good pixel structure management, so the easiest solution was to just force top-bottom format. It is trivial to add side-by-side format but I'm just worried about how efficient it would be.
As for the issue of left and right images being in the wrong order, that's an easy fix, although there were no issues when I was testing it. Would you be able to create an example blender file and rendered images to show this? It could be a settings issue that I could create a fix for.
Thanks!

**Comment by yes2077** [comment]
It may seem that everything is alright, but when I rendered objects close to camera, I felt like something is wrong. I flipped over my phone and quality of image significantly increased

Here are 2 random pictures I found in google, where top is left eye and bottom is right eye

![image1](https://user-images.githubusercontent.com/59512184/71772659-b8f9d200-2f5f-11ea-8c16-2634a2246b73.jpg)

![image2](https://user-images.githubusercontent.com/59512184/71772665-ce6efc00-2f5f-11ea-9f1a-66a4396d67e3.png)

And my rendered image (look at cyan cube), top is right eye, bottom is left eye

![Render Result ](https://user-images.githubusercontent.com/59512184/71772655-a7182f00-2f5f-11ea-8668-7e1b4e59c479.png)

[Monkeys.zip](https://github.com/EternalTrail/eeVR/files/4022645/Monkeys.zip)

This isn't really a problem, because I can just mirror it there

![image3](https://user-images.githubusercontent.com/59512184/71772678-14c45b00-2f60-11ea-92ae-796d2011b6b8.jpg)

**Comment by EternalTrail** [comment]
Hi, as of commit 1b30c8e side-by-side support has been added. As for swapping the images, I don't have enough reason to implement a fix since no one else seems to have this problem and it might only be specific to your platform/set-up. This issue is now closed.

**Comment by PaulNLNL** [comment]
Great script! Thank you.

On the left right issue. I thought I had that problem as well and manually swapped LR in an image editor. It did fix a perceived problem for a specific object in the centre of the scene. However other objects more to the side seemed to get worse. I wonder if this may be related to the screen distance. I did notice something strange though in the actual rendering of left and right.  The actual shapes seem to be different. Notice these two images where left and right have mostly the same particles but near the white floor there are a few particles that are different. 
![image](https://user-images.githubusercontent.com/84221938/118352225-8d79f500-b560-11eb-98e3-b1c7b031ce79.png) 
![image](https://user-images.githubusercontent.com/84221938/118352274-de89e900-b560-11eb-86c5-12ec6d0600ea.png)

Particle settings:
![image](https://user-images.githubusercontent.com/84221938/118352397-856e8500-b561-11eb-9fd7-b2b021546a89.png)
I am sorry I do not yet have a simple blender file to share that has the issue.
