### ISSUE TITLE
About Keyframes and Camera rotation

### ISSUE THREAD

**Issue by jehuty1980** [EternalTrail/eeVR#9]
First, awesome script!

There are 2 key issues I'd like to mention:
1, when using camera motion(action), the rendering result will just be like a picture mixed with 6 same pictures. I think it's because of the keyframes. When using keyframes on Camera, one cannot really change the direction of the camera without inserting a new keyframe, and you will get 6 same pics from the 'front' view.
I hoped to fix this problem as following:
1>add a new camera obj, with the same parameters of the old one;
2>activate it;
3>using the new one to render scene;
4>remove it;
5>activate the old one.
but, I cannot find an API to do the 2nd step. Most likely to do this is "bpy.ops.view3d.object_as_camera()", but when executing, there will be a context error.

2. when the rotation Y of the camera is not zero, the rendering result will be distorted. I think it's because of the find_direction_offsets() method treats the Y value as zero by default.

By the way, the output file format should not be TIFF, the compositing node should not be used, or it will crash.

Thank you!

**Comment by coderofsalvation** [comment]
awesome script indeed.

Small question: does this mean keyframed camera-animations are not supported?

**Comment by EternalTrail** [comment]
Keyframing the camera angles is not supported at the moment although there are possible fixes without adding and removing cameras, I'm not currently actively working on this project. As for the Y axis distorting the final result, I'm very aware of it I just couldn't figure out the maths behind rotating the camera with Y values other than 0 in a short amount of time. I might add try improving this in the future if someone doesn't do it before me.

**Comment by coderofsalvation** [comment]
No worries, Thanks for your answer.

**Comment by jehuty1980** [comment]
> Keyframing the camera angles is not supported at the moment although there are possible fixes without adding and removing cameras, I'm not currently actively working on this project. As for the Y axis distorting the final result, I'm very aware of it I just couldn't figure out the maths behind rotating the camera with Y values other than 0 in a short amount of time. I might add try improving this in the future if someone doesn't do it before me.

Could you tell me about the idea of those possible fixes? Maybe I'll give a try.

**Comment by EternalTrail** [comment]
When you start the render, insert an empty into the scene, set the parent of the camera to that empty, when a render is finished unparent and move to the next frame. This was suggested to me by someone  who had run into this issue previously. I might give it a try myself today, together with some other fixes people have been asking for.

**Comment by EternalTrail** [comment]
As of commits c786374  & 1946b07 both of the issues stated are fixed. The issue is now closed.

**Comment by coderofsalvation** [comment]
awesome!
